config/routes.rb
Rails.application.routes.draw do
  # require 'sidekiq/web'

  # mount Ckeditor::Engine => "/ckeditor"
  # mount Rswag::Ui::Engine => "/api/docs"
  # mount Rswag::Api::Engine => "/api/docs"
  # mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  # mount Sidekiq::Web => "/sidekiq"
  
  root "dashboards#home_page"
  get :skill, to: "dashboards#skill"

  # namespace :admin do
  #   root "dashboard#index"

  #   devise_for :admins, path: "", path_names: { sign_in: "login", sign_out: "logout" },
  #     skip: [:registrations, :passwords]

  #   resources :posts do
  #     member do
  #       delete :delete_image_attachment
  #       get :copy
  #     end
  #   end
  #   resources :tags
  #   resources :categories do
  #     member do
  #       delete :delete_image_attachment
  #     end
  #   end

  #   resources :reports, only: :index
  # end

  # namespace :api do
  #   namespace :v1 do
  #     resources :posts, only: [:index, :show] do
  #       collection do
  #         get :slugs
  #         get :preview
  #       end

  #       member do
  #         get :track_views
  #       end
  #     end
  #     resources :categories, only: :index
  #     resources :reports, only: :create

  #     get :subscribed, to: "subscribe#subscribed"
  #     get :unsubscribe, to: "subscribe#unsubscribe"
  #     get :confirm_subscribed, to: "subscribe#confirm_subscribed"
  #   end
  # end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/dashboards_controller.rb
# frozen_string_literal: true

class DashboardsController < ApplicationController
  def home_page
  end

  def skill
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/dashboards/home_page.html.erb
<% provide :description, "Ngày đó chở theo ánh mắt trong trẻo nhìn cuộc đời không một chút hoài nghi, thế giới trong đồng tử của một đứa trẻ con bao giờ cũng đẹp tuyệt." %>

<div class="container">
  <%= image_tag("avatar.jpg", alt: "logo", class: "logo") %>
  <div class="left">
    <div class="background-rotate">
      <div class="bg-rotate"></div>
    </div>
    <div class="list-left">
      <div class="group" id="group_item_0"></div>
      <div class="group" id="group_item_1"></div>
      <div class="group" id="group_item_2"></div>
    </div>
  </div>
  <div class="right">
    <p align="center">
      <img
        src="https://readme-typing-svg.herokuapp.com?color=%2336BCF7&center=true&vCenter=true&lines=Hi,I'm+Hao+Truong!;Ruby+Developer+from+Viet+Nam;Nice+to+meet+you...!"
      />
    </p>
    <p align="center">
      <%= image_tag("Developer.gif",alt: "image dev") %>
    </p>
  </div>
  <div class="menu">
    <ul>
      <li class="cursor">
        <%= link_to "https://www.facebook.com/haotv03/", target: "_blank" do %>
          <img src="<%= asset_path("icons/fb.svg") %>" alt="icon-fb">
        <% end %>
      <li class="cursor">
        <%= link_to "https://www.linkedin.com/in/haotv03/", target: "_blank" do %>
          <img src="<%= asset_path("icons/linkedin.svg") %>" alt="icon-linkedin">
        <% end %>
      </li>
      <li class="cursor">
        <%= link_to "https://github.com/haotruong2204", target: "_blank" do %>
          <img src="<%= asset_path("icons/github.svg") %>" alt="icon-github">
        <% end %>
      </li>
      <li class="cursor">
        <%= link_to skill_path do %>
          <img src="<%= asset_path("icons/terminal.svg") %>" alt="icon-terminal">
        <% end %>
      </li>
    </ul>
  </div>
</div>

app/views/dashboards/skill.html.erb
<div class="container">
  <div class="bg-rotate"></div>
  <div class="header" style="margin: 10px 30px">
    <img src="avatar.jpg" class="logo" />
    <ul>
      <li>HOME</li>
    </ul>
  </div>
  <div class="list-img">
    <div class="item" id="item_0"><img src="1.png" /></div>
    <div class="item" id="item_1"><img src="4.png" /></div>
    <div class="item" id="item_2"><img src="2.png" /></div>
    <div class="item" id="item_3"><img src="3.png" /></div>
    <div class="item" id="item_4"><img src="4.png" /></div>
  </div>
  <div class="content">
    <div class="item" id="content_0">
      <h1>ITEM 0</h1>
      <p>Tính rủ anh đi cháy phố, chưa kịp đón a mà xe đã cháy</p>
      <p>
        <button>TRUY VẬP <i class="fa-solid fa-arrow-right"></i></button>
      </p>
    </div>

    <div class="item" id="content_1">
      <h1>ITEM 1</h1>
      <p>Tính rủ anh đi cháy phố, chưa kịp đón a mà xe đã cháy</p>
      <p>
        <button>TRUY VẬP <i class="fa-solid fa-arrow-right"></i></button>
      </p>
    </div>

    <div class="item" id="content_2">
      <h1>ITEM 2</h1>
      <p>Tính rủ anh đi cháy phố, chưa kịp đón a mà xe đã cháy</p>
      <p>
        <button>TRUY VẬP <i class="fa-solid fa-arrow-right"></i></button>
      </p>
    </div>

    <div class="item" id="content_3">
      <h1>ITEM 3</h1>
      <p>Tính rủ anh đi cháy phố, chưa kịp đón a mà xe đã cháy</p>
      <p>
        <button>TRUY VẬP <i class="fa-solid fa-arrow-right"></i></button>
      </p>
    </div>

    <div class="item" id="content_4">
      <h1>ITEM 4</h1>
      <p>Tính rủ anh đi cháy phố, chưa kịp đón a mà xe đã cháy</p>
      <p>
        <button>TRUY VẬP <i class="fa-solid fa-arrow-right"></i></button>
      </p>
    </div>
  </div>
  <div class="next">
    <button id="prev"><i class="fa-solid fa-angle-left"></i></button>
    <button id="next"><i class="fa-solid fa-angle-right"></i></button>
  </div>
  <div class="dot">
    <div id="dot_0"></div>
    <div id="dot_1"></div>
    <div id="dot_2"></div>
    <div id="dot_3"></div>
    <div id="dot_4"></div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Home | haotruong.dev</title>
    <meta name="description" content="<%= yield(:description) %>">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= favicon_link_tag asset_path("favicon.png"), rel: "icon", type: "image/x-icon" %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>